# Generated by Django 2.2.5 on 2021-08-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210727_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=1, upload_to='avatar'),
            preserve_default=False,
        ),
    ]
